name: OmniTools
version: ${project.version}
main: dev.nuer.ot.OmniTools
api-version: 1.13
author: Nuer
commands:
  omnitools:
    usage: /<command>
    description: Base command for OmniTools, use /ot h for command help.
    aliases: [ot, otools, omnit, omni]