1:
  name: "&6Omni Tool"
  lore:
    - "&7 "
    - "&aOmni Tools are know to have special traits,"
    - "&athey can mine any type of block easily..."
  enchantments:
    - durability:3
    - dig_speed:5
  item-flags:
    - hide_unbreakable